name: flutter_facebook_app_links
description: A Flutter plugin to catch deferred deep links from Facebook ads with FB App Links SDK and GDPR consent support.
version: 3.1.1
homepage: https://github.com/twinsunllc/flutter_facebook_app_links

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: ">=3.2.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: it.remedia.flutter_facebook_app_links
        pluginClass: FlutterFacebookAppLinksPlugin
      ios:
        pluginClass: FlutterFacebookAppLinksPlugin
